services:
  postgres:
    image: postgres:18.1-alpine
    container_name: melkar-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: melkar
      POSTGRES_USER: melkar
      POSTGRES_PASSWORD: melkar123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
